# Generated by Django 5.2.4 on 2025-08-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Имя пользователя"
            ),
        ),
    ]
