# Generated by Django 5.2.4 on 2025-08-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
