# Generated by Django 5.2.4 on 2025-08-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Укажите цену курса в USD",
                max_digits=10,
                verbose_name="Цена курса",
            ),
        ),
    ]
